export const WELCOME_LOADING = "REGISTER LOADING";
export const WELCOME_FAIL = "REGISTER FAIL";
export const WELCOME_SUCCESS = "WELCOME SUCCESS";
export const CLEAR_AUTH_STATE = "CLEAR_STATE";
export const LOGIN_LOADING = "LOGIN LOADING";
export const LOGIN_FAIL = "LOGIN FAIL";
export const LOGIN_SUCCESS = "LOGIN SUCCESS";
export const CLEAR_MODE = "DEVELOPER MODE OFF";
export const WEEK_LOADING = "WEEK INFO LOADING";
export const WEEK_SUCCESS = "WEEK INFO RETRIEVED";
export const WEEK_FAILED = "WEEK INFO FAILED";
export const DASH_CLEAR = "ONBOARD COMPLETED";



