export const REGISTER_LOADING = "REGISTER LOADING";
export const REGISTER_FAIL = "REGISTER FAIL";
export const REGISTER_SUCCESS = "REGISTER SUCCESS";
export const CLEAR_AUTH_STATE = "CLEAR_STATE";
export const LOGIN_LOADING = "LOGIN LOADING";
export const LOGIN_FAIL = "LOGIN FAIL";
export const LOGIN_SUCCESS = "LOGIN SUCCESS";
export const CLEAR_MODE = "DEVELOPER MODE OFF";
export const WEEK_LOADING = "WEEK INFO LOADING";
export const WEEK_SUCCESS = "WEEK INFO RETRIEVED";
export const WEEK_FAILED = "WEEK INFO FAILED";
export const ONBOARD_COMPLETE = "ONBOARD COMPLETED";
export const SOCIAL_LOADING = "SOCIAL INFO LOADING";
export const SOCIAL_SUCCESS = "SOCIAL INFO RETRIEVED";
export const SOCIAL_FAILED = "SOCIAL INFO FAILED";


